apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: invoice-ingress
  namespace: invoice-management
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: invoice.example.com  # replace with your host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: invoice-app-service
                port:
                  number: 80

