apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-mysql
  namespace: invoice-management
  labels:
    app: invoice-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-mysql
  template:
    metadata:
      labels:
        app: invoice-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: invoice-secrets
                  key: datasource.password
            - name: MYSQL_DATABASE
              value: invoicemanagementdb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}

